const PIZZACONSTANTS = {
  'SMALLPIZZA': 'SMALL',
  'SMALLPIZZASIZE': 10,
  'SMALLPIZZAPRICE': 269.99,
  'MEDIUMPIZZA': 'MEDIUM',
  'MEDIUMPIZZASIZE': 12,
  'MEDIUMPIZZAPRICE': 322.99,
  'LARGEPIZZA': 'LARGE',
  'LARGEPIZZASIZE': 15,
  'LARGEPIZZAPRICE': 394.99
};

module.exports = PIZZACONSTANTS;